name: myspace_flutter_tool
description: "MySpace Flutter Tool"
homepage: www.shoh.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  repositories:
    path: packages/repositories

  cupertino_icons: ^1.0.8

  # FCode packages START
  myspace_design_system: ^0.0.1
  myspace_core: ^0.0.1
  # FCode packages END

  window_manager: ^0.4.3
  yaml: ^3.1.3
  go_router: ^14.6.3
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  pub_api_client: ^3.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true